// <auto-generated />
using EFCore5_SplitQuery;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFCore5_SplitQuery.Migrations
{
    [DbContext(typeof(BancoContexto))]
    [Migration("20210403122813_SetupInicial")]
    partial class SetupInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFCore5_SplitQuery.Etapa", b =>
                {
                    b.Property<int>("EtapaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cidade")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EtapaId");

                    b.ToTable("Etapas");

                    b.HasData(
                        new
                        {
                            EtapaId = 1,
                            Cidade = "Moto GP Qatar"
                        },
                        new
                        {
                            EtapaId = 2,
                            Cidade = "Moto GP Italia Mugello"
                        });
                });

            modelBuilder.Entity("EFCore5_SplitQuery.Piloto", b =>
                {
                    b.Property<int>("PilotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EtapaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PilotoId");

                    b.HasIndex("EtapaId");

                    b.ToTable("Pilotos");

                    b.HasData(
                        new
                        {
                            PilotoId = 1,
                            EtapaId = 1,
                            Nome = "Marque Marques",
                            Pais = "Espanha"
                        },
                        new
                        {
                            PilotoId = 2,
                            EtapaId = 1,
                            Nome = "Valentino Rossi",
                            Pais = "Italia"
                        },
                        new
                        {
                            PilotoId = 3,
                            EtapaId = 1,
                            Nome = "Franco Morbidelli",
                            Pais = "Italia"
                        },
                        new
                        {
                            PilotoId = 4,
                            EtapaId = 1,
                            Nome = "Miguel Oliveira",
                            Pais = "Portugal"
                        },
                        new
                        {
                            PilotoId = 5,
                            EtapaId = 2,
                            Nome = "Danilo Petrucci",
                            Pais = "Espanha"
                        },
                        new
                        {
                            PilotoId = 6,
                            EtapaId = 2,
                            Nome = "Takkaki Nakagami",
                            Pais = "Japao"
                        },
                        new
                        {
                            PilotoId = 7,
                            EtapaId = 2,
                            Nome = "Luca Marini",
                            Pais = "Italia"
                        },
                        new
                        {
                            PilotoId = 8,
                            EtapaId = 2,
                            Nome = "Iker Lecuona",
                            Pais = "Espanha"
                        },
                        new
                        {
                            PilotoId = 9,
                            EtapaId = 2,
                            Nome = "Lorenzo Salvadori",
                            Pais = "Italia"
                        });
                });

            modelBuilder.Entity("EFCore5_SplitQuery.Piloto", b =>
                {
                    b.HasOne("EFCore5_SplitQuery.Etapa", "Etapa")
                        .WithMany("Pilotos")
                        .HasForeignKey("EtapaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Etapa");
                });

            modelBuilder.Entity("EFCore5_SplitQuery.Etapa", b =>
                {
                    b.Navigation("Pilotos");
                });
#pragma warning restore 612, 618
        }
    }
}
